required = ["gocv.io/x/gocv/openvino"]

[[constraint]]
  name = "gocv.io/x/gocv"
  branch = "dev"

[[constraint]]
  name = "github.com/eclipse/paho.mqtt.golang"
  version = "1.1.1"

[[constraint]]
  name = "github.com/google/uuid"
  version = "v1.1.0"

[prune]
  go-tests = true
  unused-packages = true
